"""Record exactly what was computed, so the artifact can be reproduced and the
reproduction verified bit for bit.

    python3 analysis/manifest.py > data/MANIFEST.md

The raw CSVs and the SQLite database are gitignored: together they are several
hundred megabytes, which does not belong in this repository. What is committed
is (a) the generating scripts, (b) the derived summary tables in data/summary/
that every claim in REPORT.md is computed from, and (c) this manifest, which
pins the sizes and SHA-256 digests so a regeneration can be checked against the
run the report describes.
"""

import hashlib
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")

FILES = ["disc_ordered.csv", "reg_ordered.csv", "disc_window.csv",
         "quadratic_fields.sqlite"]
SCRIPTS = ["gen_disc_ordered.gp", "gen_reg_ordered.gp", "gen_disc_window.gp",
           "verify_extremality.gp", "grh_spotcheck.gp"]


def sha256(path, chunk=1 << 20):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        while True:
            b = f.read(chunk)
            if not b:
                break
            h.update(b)
    return h.hexdigest()


def version(cmd, args):
    try:
        out = subprocess.run([cmd] + args, capture_output=True, text=True,
                             timeout=30)
        return (out.stdout + out.stderr).strip().splitlines()[0]
    except Exception as e:
        return f"(unavailable: {e})"


def main():
    print("# Data manifest\n")
    print("Generated by `python3 analysis/manifest.py`.\n")

    print("## Environment\n")
    print(f"* PARI/GP: `{version('gp', ['--version-short'])}`")
    print(f"* Python: `{sys.version.split()[0]}`")
    try:
        import numpy
        print(f"* numpy: `{numpy.__version__}`")
    except ImportError:
        pass
    try:
        import scipy
        print(f"* scipy: `{scipy.__version__}`")
    except ImportError:
        pass
    try:
        rev = subprocess.run(["git", "rev-parse", "HEAD"], cwd=ROOT,
                             capture_output=True, text=True).stdout.strip()
        print(f"* git commit at manifest time: `{rev}`")
    except Exception:
        pass

    print("\n## Enumeration bounds\n")
    print("| dataset | script | bound | completeness |")
    print("|---|---|---|---|")
    print("| `disc_ordered.csv` | `data/gen_disc_ordered.gp` | `XMAX = 10^7` | "
          "every fundamental discriminant `0 < D <= 10^7` |")
    print("| `reg_ordered.csv` | `data/gen_reg_ordered.gp` | `TMAX = 2*10^6` | "
          "every fundamental discriminant with `Tr(eps_D) <= 2*10^6`, "
          "equivalently `eps_D <= 2*10^6`; reaches `D ~ 4*10^12` |")
    print("| `disc_window.csv` | `data/gen_disc_window.gp` | "
          "`DSTART = 10^12`, `NWANT = 250000` | 250000 consecutive fundamental "
          "discriminants from `10^12` upward (control for D-scale) |")

    print("\n## Files\n")
    print("| file | bytes | rows | sha256 |")
    print("|---|---:|---:|---|")
    for name in FILES:
        p = os.path.join(DATA, name)
        if not os.path.exists(p):
            print(f"| `{name}` | — | — | *(not present)* |")
            continue
        size = os.path.getsize(p)
        if name.endswith(".csv"):
            with open(p, "rb") as f:
                rows = sum(1 for _ in f) - 1        # minus header
            rows = f"{rows:,}"
        else:
            rows = "—"
        print(f"| `{name}` | {size:,} | {rows} | `{sha256(p)}` |")

    print("\n## Generating scripts (digests, so the manifest pins the code too)\n")
    print("| script | sha256 |")
    print("|---|---|")
    for name in SCRIPTS:
        p = os.path.join(DATA, name)
        if os.path.exists(p):
            print(f"| `data/{name}` | `{sha256(p)}` |")

    print("\n## Reproduction\n")
    print("```bash")
    print("cd data")
    print("gp -q gen_disc_ordered.gp > disc_ordered.csv   # ~20 min, 4 threads")
    print("gp -q gen_reg_ordered.gp  > reg_ordered.csv    # ~2 h,   4 threads")
    print("gp -q gen_disc_window.gp  > disc_window.csv    # ~5 min, 4 threads")
    print("cd ..")
    print("python3 analysis/build_db.py                   # -> data/quadratic_fields.sqlite")
    print("python3 analysis/compare.py                    # -> data/summary/*.csv")
    print("```")
    print("\nThe class groups are computed by `quadclassunit`, which uses Bach's")
    print("bound and is therefore conditional on GRH. `data/grh_spotcheck.gp`")
    print("recomputes a sample with `bnfinit` + `bnfcertify`, which is")
    print("unconditional; see REPORT.md for the result.")


if __name__ == "__main__":
    main()
